# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2956c561eec71cccd1a09b4798b68ce998b267efa8991df68a6394b062c3ffed1de125b0b22d2938f2b5fb16bee1333eeee348d4bb005ad36ff44e844bccd3a0

test:
  secret_key_base: 867d8ac08bd5ec3754efbf842b93ae009aefa8d211e680457102d5de81334d8e79f15d6745f552a8b1dc29e77536ead18f377758e2fb0b7e8bac999c8bf3ed80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
